; Chapter 2: 複数サーボの同時制御（同期できていない例）
; PlatformIO 用プロジェクト設定ファイル

[platformio]
src_dir = .

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
lib_deps =
    adafruit/Adafruit PWM Servo Driver Library
