; Chapter 1: サーボキャリブレーション用スケッチ
; PlatformIO 用プロジェクト設定ファイル

[platformio]
src_dir = .

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
lib_deps =
    adafruit/Adafruit PWM Servo Driver Library
